config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/customers')
  resources :customers, only: [:index]
  resources :customer_imports, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_one :vehicle, dependent: :destroy

  delegate :name, :length_feet, to: :vehicle, prefix: true
  delegate :vehicle_type, to: :vehicle

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/customer_import.rb
# frozen_string_literal: true

class CustomerImport
  attr_reader :file_text

  RECOGNIZED_DELIMITERS = [',', '|'].freeze
  REQUIRED_COLUMN_ORDER = %i[first_name last_name email vehicle_type vehicle_name vehicle_length].freeze
  LENGTH_PARSING_REGEX = /\d+/

  UnparseableFile = Class.new(StandardError)

  def initialize(file_text)
    @file_text = file_text.strip
  end

  def create!
    ActiveRecord::Base.transaction do
      normalized_rows.each do |normalized_row|
        customer = upsert_customer!(normalized_row)
        create_vehicle!(customer: customer, normalized_row: normalized_row)
      end
    end
  end

  def normalize_length(length)
    return length if length.is_a? Integer

    return LENGTH_PARSING_REGEX.match(length)[0].to_i if LENGTH_PARSING_REGEX.match?(length)
  end

  private

  def upsert_customer!(normalized_row)
    Customer.find_or_initialize_by(email: normalized_row[:email]).tap do |customer|
      customer.first_name = normalized_row[:first_name]
      customer.last_name = normalized_row[:last_name]
      customer.save!
    end
  end

  def create_vehicle!(customer:, normalized_row:)
    Vehicle.find_or_create_by!(
      customer: customer,
      name: normalized_row[:vehicle_name],
      vehicle_type: normalized_row[:vehicle_type],
      length_feet: normalized_row[:vehicle_length]
    )
  end

  def original_rows
    @_original_rows ||= file_text.split(/\n/)
  end

  def parsed_rows
    original_rows.map do |original_row|
      Hash[REQUIRED_COLUMN_ORDER.zip(original_row.split(file_delimiter))]
    end
  end

  def normalized_rows
    parsed_rows.each do |parsed_row|
      parsed_row[:vehicle_length] = normalize_length(parsed_row[:vehicle_length])
    end
  end

  def file_delimiter
    return @_delimiter if @_delimiter

    RECOGNIZED_DELIMITERS.each do |delimiter|
      attempted_parsed_row = original_rows.first.split(delimiter)

      next unless attempted_parsed_row.length == REQUIRED_COLUMN_ORDER.length

      @_delimiter = delimiter

      return @_delimiter
    end

    raise UnparseableFile, "Must include following columns: #{REQUIRED_COLUMN_ORDER.join(' ')}"
  end
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  include PGEnum(vehicle_type: %w[campervan sailboat motorboat RV bicycle])
  belongs_to :customer
  validates :name, presence: true
  validates :vehicle_type, presence: true
  validates :length_feet, presence: true, numericality: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/customer_imports_controller.rb
# frozen_string_literal: true

class CustomerImportsController < ApplicationController
  before_action :validate_filetype

  InvalidFileType = Class.new(StandardError)

  rescue_from ActionController::ParameterMissing, with: :bad_request
  rescue_from InvalidFileType, with: :unprocessable_entity

  VALID_MIME_TYPES = ['text/plain'].freeze

  def create
    CustomerImport.new(file_text).create!
  rescue ActiveRecord::RecordInvalid
    flash[:error] = 'Invalid data in file. Customers not created'
  ensure
    redirect_to customers_path
  end

  private

  def validate_filetype
    raise InvalidFileType unless VALID_MIME_TYPES.include? file_param.content_type
  end

  def file_text
    file_param.read
  end

  def file_param
    params.require(:file)
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @sorted_customers = SortedCustomers.new(sort_column: sort_column, original_sort_direction: sort_direction)
  end

  private

  def sort_direction
    params.permit(:sort_direction)[:sort_direction]&.to_sym
  end

  def sort_column
    params.permit(:sort_column)[:sort_column]&.to_sym
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/customer_imports_helper.rb
# frozen_string_literal: true

module CustomerImportsHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/views/customers/_customer.html.haml
%tr
  %td
    = customer.full_name
  %td
    = customer.email
  %td.text-capitalize
    = customer.vehicle_type
  %td
    = customer.vehicle_name
  %td
    = customer.vehicle_length_feet

app/views/customers/_sortable_header.html.haml
- sort_dir = @sorted_customers.sort_column == column_name && @sorted_customers.sort_direction == :asc ? :desc : :asc
= form_tag customers_path, method: :get do |f|
  = hidden_field_tag :sort_column, column_name
  = hidden_field_tag :sort_direction, sort_dir
  = submit_tag column_name.to_s.titleize, class: "border-0 fw-bold"
  %i.fa.fa-fw.fa-sort

app/views/customers/index.html.haml
.navbar.mb-1.navbar-dark.bg-dark
  = link_to "Outdoor.sy", root_path, class: "navbar-brand mx-5"

.container.pt-2
  %h3 Customers

  %table.table.table-striped
    %tr
      %th
        = render partial: "sortable_header", locals: { column_name: :full_name }
      %th
        Email
      %th
        = render partial: "sortable_header", locals: { column_name: :vehicle_type }
      %th
        Vehicle Name
      %th
        Vehicle Length (ft)
    = render partial: "customer", collection: @sorted_customers.customers

  %h3 Import

  = form_with(url: customer_imports_path, method: :post) do |f|
    .row.mb-4
      .col-auto
        = f.label :file, class: 'col-form-label'
      .col-auto
        = f.file_field :file, class: "form-control"
      .col-auto
        = f.submit "Import Customers", class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Outdoorsy
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    %link{rel: :stylesheet, href: "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"}
  %body
    - flash.each do |type, message|
      .alert{class: "alert-#{type}"}
        = message
    = yield